routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\TableController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Front\FrontMenuController;
use App\Http\Controllers\Admin\ReservationController;
use App\Http\Controllers\Front\FrontWelcomeController;
use App\Http\Controllers\Front\FrontCategoryController;
use App\Http\Controllers\Front\FrontReservationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');


Route::get('/', [FrontWelcomeController::class, 'index']);
Route::get('/menu', [FrontMenuController::class, 'index'])->name('menu.index');
Route::get('/categories', [FrontCategoryController::class, 'index'])->name('categories.index');
Route::get('/categories/{category}', [FrontCategoryController::class, 'show'])->name('categories.show');
Route::get('/reservation/step-one', [FrontReservationController::class, 'stepOne'])->name('reservation.step-one');
Route::post('/reservation/step-one', [FrontReservationController::class, 'storeStepOne'])->name('reservation.store.step-one');
Route::get('/reservation/step-two', [FrontReservationController::class, 'stepTwo'])->name('reservation.step-two');
Route::post('/reservation/step-two', [FrontReservationController::class, 'storeStepTwo'])->name('reservation.store.step-two');

// Admin

Route::middleware(['auth', 'admin'])->name('admin.')->prefix('admin')->group(function(){
    Route::get('/', [AdminController::class, 'index'])->name('index');
    Route::resource('/categories', CategoryController::class);
    Route::resource('/menus', MenuController::class);
    Route::resource('/tables', TableController::class);
    Route::resource('/reservations', ReservationController::class);
});



require __DIR__.'/auth.php';

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Http/Controllers/Admin/TableController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\TableStoreRequest;
use App\Models\Table;
use Illuminate\Http\Request;

class TableController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tables = Table::all();
        return view('admin.tables.index', compact('tables'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.tables.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TableStoreRequest $request)
    {

        $Table = new Table($request->validated());
        $Table->save();
        return redirect(route('admin.tables.index'))->with('success','');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Table $table)
    {
        return view('admin.tables.edit', compact('table'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(TableStoreRequest $request, Table $table)
    {
        $table->fill($request->all());
        $table->save();

        return redirect(route('admin.tables.index'))->with('warning','');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Table $table)
    {
        $table->delete();
        return redirect(route('admin.tables.index'))->with('danger','');
    }
}

resources/views/admin/tables/create.blade.php
@extends('layouts.mainAdmin')
@section('content')

<div class="main">
    <h1>Stoliki</h1>

    <div class="">
        <a class="btn btn-dark button-back" href="{{ route('admin.tables.index') }}" role="button">Powrót do karegori</a>

    </div>

    <div class="smal main">
        <form method="POST" action="{{ route('admin.tables.store') }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="name" class="form-label">Nazwa</label>
                <input class="form-control @error('name') is-invalid @enderror" type="text" name="name" placeholder="Podaj nazwe">
                @error('name')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="name" class="form-label">Liczba gości</label>
                <input class="form-control @error('guest_number') is-invalid @enderror" type="text" name="guest_number" placeholder="Podaj liczbe osób">
                @error('guest_number')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="exampleFormControlSelect1">Miejsce</label>
                <select class="form-control" id="exampleFormControlSelect1" name="location">
                    @foreach (App\Enums\TableLocation::cases() as $location)
                        <option value="{{ $location->value }}">{{ $location->name }}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label for="exampleFormControlSelect1">Status</label>
                <select class="form-control" id="exampleFormControlSelect1" name="status">
                    @foreach (App\Enums\TableStatus::cases() as $status)
                        <option value="{{ $status->value }}">{{ $status->name }}</option>
                    @endforeach
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
@endsection

resources/views/admin/tables/edit.blade.php
@extends('layouts.mainAdmin')
@section('content')

<div class="main">
    <h1>Categories</h1>

    <div class="">
        <a class="btn btn-dark button-back" href="{{ route('admin.tables.index') }}" role="button">Powrót do karegori</a>

    </div>

    <div class="smal main">
        <form method="POST" action="{{ route('admin.tables.update', $table->id) }}" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group">
                <label for="name" class="form-label">Nazwa</label>
                <input class="form-control" type="text" name="name" value="{{ $table->name }}">
            </div>
            <div class="form-group">
                <label for="name" class="form-label">Ilość osób	</label>
                <input class="form-control" type="text" name="guest_number" value="{{ $table->guest_number }}">
            </div>
            <div class="form-group">
                <label for="exampleFormControlSelect1">Miejsce</label>
                <select class="form-control" id="exampleFormControlSelect1" name="location">
                    @foreach (App\Enums\TableLocation::cases() as $location)
                        <option value="{{ $location->value }}">{{ $location->name }}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label for="exampleFormControlSelect1">Status</label>
                <select class="form-control" id="exampleFormControlSelect1" name="status">
                    @foreach (App\Enums\TableStatus::cases() as $status)
                        <option value="{{ $status->value }}">{{ $status->name }}</option>
                    @endforeach
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
@endsection

resources/views/admin/tables/index.blade.php
@extends('layouts.mainAdmin')
@section('content')


<div class="main">
    <h1>Stoliki</h1>

    <div class="">
        <a class="btn btn-dark" href="{{ route('admin.tables.create') }}" role="button">Nowa kategoria</a>
    </div>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Nr</th>
                <th scope="col">Nazwa</th>
                <th scope="col">Ilość osób</th>
                <th scope="col">Status</th>
                <th scope="col">Miejsce</th>
                <th scope="col" id="table_akcja">Akcja</th>
            </tr>
            </thead>
            <tbody>
                @foreach ($tables as $table )
                    <tr>
                        <th scope="row">{{ $loop->iteration }}</th>
                        <td>{{ $table->name }}</td>
                        <td>{{ $table->guest_number }}</td>
                        <td>{{ $table->status }}</td>
                        <td>{{ $table->location }}</td>
                        <td>
                            <a class="btn btn-dark" href="{{ route('admin.tables.edit', $table->id) }}" role="button">Edytuj</a>
                            <form method="POST" action="{{ route('admin.tables.destroy', $table->id) }}" onsubmit="return confirm('Na pewno chcesz usunąć?');">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger" type="submit" role="button">Usuń</button>
                        </form>
                        </td>
                    </tr>
                @endforeach
        </tbody>
    </table>
</div>
@endsection