routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\TableController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Front\FrontMenuController;
use App\Http\Controllers\Admin\ReservationController;
use App\Http\Controllers\Front\FrontWelcomeController;
use App\Http\Controllers\Front\FrontCategoryController;
use App\Http\Controllers\Front\FrontReservationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');


Route::get('/', [FrontWelcomeController::class, 'index']);
Route::get('/menu', [FrontMenuController::class, 'index'])->name('menu.index');
Route::get('/categories', [FrontCategoryController::class, 'index'])->name('categories.index');
Route::get('/categories/{category}', [FrontCategoryController::class, 'show'])->name('categories.show');
Route::get('/reservation/step-one', [FrontReservationController::class, 'stepOne'])->name('reservation.step-one');
Route::post('/reservation/step-one', [FrontReservationController::class, 'storeStepOne'])->name('reservation.store.step-one');
Route::get('/reservation/step-two', [FrontReservationController::class, 'stepTwo'])->name('reservation.step-two');
Route::post('/reservation/step-two', [FrontReservationController::class, 'storeStepTwo'])->name('reservation.store.step-two');

// Admin

Route::middleware(['auth', 'admin'])->name('admin.')->prefix('admin')->group(function(){
    Route::get('/', [AdminController::class, 'index'])->name('index');
    Route::resource('/categories', CategoryController::class);
    Route::resource('/menus', MenuController::class);
    Route::resource('/tables', TableController::class);
    Route::resource('/reservations', ReservationController::class);
});



require __DIR__.'/auth.php';

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Reservation.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Reservation extends Model
{
    use HasFactory;

    protected $fillable = [
        'first_name',
        'last_name',
        'email',
        'phone',
        'res_date',
        'table_id',
        'guest_number'
    ];

    protected $dates = [
        'res_date'
    ];

    public function table()
    {
        return $this->belongsTo(Table::class);
    }
}

app/Http/Controllers/Admin/ReservationController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Table;
use App\Enums\TableStatus;
use App\Models\Reservation;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;
use App\Http\Requests\ReservationStoreRequest;

class ReservationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $reservations = Reservation::all();
        return view('admin.reservations.index', compact('reservations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tables = Table::where('status', TableStatus::Dostepne)->get();
        return view('admin.reservations.create', compact('tables'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ReservationStoreRequest $request)
    {

        $table = Table::findOrFail($request->table_id);
        if($request->guest_number > $table->guest_number){
            return back()->with('warning', 'Proszę dopasuj liczbę gości do liczby miejsc przy stoliku');
        }

        $request_date = Carbon::parse($request->res_date);
        foreach ($table->reservations as $res) {
            if ($res->res_date->format('H') == $request_date->format('H')){
                return back()->with('warning2', 'Ten termin jest już zarezerwowany');
            }
        }


        $reservation = new Reservation($request->validated());
        $reservation->save();
        return redirect(route('admin.reservations.index'))->with('success','');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Reservation $reservation)
    {
        $tables = Table::all();
        return view('admin.reservations.edit', compact('reservation', 'tables'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ReservationStoreRequest $request, Reservation $reservation)
    {

        $table = Table::findOrFail($request->table_id);
        if($request->guest_number > $table->guest_number){
            return back()->with('warning', 'Proszę dopasuj liczbę gości do liczby miejsc przy stoliku');
        }
        $reservations = $table->reservations()->where('id', '!=', $reservation->id)->get();
        $request_date = Carbon::parse($request->res_date);
        foreach ($reservations as $res) {
            if ($res->res_date->format('H') == $request_date->format('H')){
                return back()->with('warning2', 'Ten termin jest już zarezerwowany');
            }
        }

        $reservation->fill($request->all());
        $reservation->save();
        return redirect(route('admin.reservations.index'))->with('warning','');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Reservation $reservation)
    {
        $reservation->delete();
        return redirect(route('admin.reservations.index'))->with('danger','');
    }
}

resources/views/admin/reservations/create.blade.php
@extends('layouts.mainAdmin')
@section('content')

    @if (session()->has('warning2'))
        <div class="alert alert-warning" role="alert">
            <span>{{ session()->get('warning2') }}</span>
        </div>
    @endif

<div class="main">
    <h1>Menu</h1>

    <div class="">
        <a class="btn btn-dark button-back" href="{{ route('admin.reservations.index') }}" role="button">Powrót do karegori</a>
    </div>

    <div class="smal main">
        <form method="POST" action="{{ route('admin.reservations.store') }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="name" class="form-label">Imie</label>
                <input class="form-control @error('first_name') is-invalid @enderror" type="text" name="first_name" placeholder="Podaj nazwe">
                @error('first_name')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="name" class="form-label">Nazwisko</label>
                <input class="form-control @error('last_name') is-invalid @enderror" type="text" name="last_name" placeholder="Podaj nazwe">
                @error('first_name')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="name" class="form-label">Email</label>
                <input class="form-control @error('email') is-invalid @enderror" type="text" name="email" placeholder="Podaj nazwe">
                @error('first_name')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="name" class="form-label">Telefon</label>
                <input class="form-control @error('phone') is-invalid @enderror" type="text" name="phone" placeholder="Podaj nazwe">
                @error('first_name')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="exampleFormControlSelect1">Stolik</label>
                <select class="form-control" id="table_id" name="table_id">
                    @foreach ($tables as $table)
                        <option value="{{ $table->id }}">{{ $table->name }} Liczba miejsc: {{ $table->guest_number }}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label for="name" class="form-label">liczba gości</label>
                <input class="form-control @error('guest_number') is-invalid @enderror" type="text" name="guest_number" placeholder="Podaj nazwe">
                @error('first_name')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="name" class="form-label">Data rezerwacji</label>
                <div class="mt-1">
                    <input type="datetime-local" id="res_date" name="res_date" class="data @error('res_date') is-invalid @enderror"/>
                    @error('first_name')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                    @error('res_date')
                        <div class="text-sm text-red-400">{{ $message }}</div>
                    @enderror
                </div>
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
@endsection

resources/views/admin/reservations/edit.blade.php
@extends('layouts.mainAdmin')
@section('content')

    @if (session()->has('warning2'))
    <div class="alert alert-warning" role="alert">
        <span>{{ session()->get('warning2') }}</span>
    </div>
    @endif

<div class="main">
    <h1>Menu</h1>

    <div class="">
        <a class="btn btn-dark button-back" href="{{ route('admin.reservations.index') }}" role="button">Powrót do karegori</a>
    </div>

    <div class="smal main">
        <form method="POST" action="{{ route('admin.reservations.update', $reservation->id) }}">
            @csrf
            @method('PUT')
            <div class="form-group">
                <label for="name" class="form-label">Imie</label>
                <input class="form-control" type="text" name="first_name" value="{{ $reservation->first_name }}">
            </div>
            <div class="form-group">
                <label for="name" class="form-label">Nazwisko</label>
                <input class="form-control" type="text" name="last_name" value="{{ $reservation->last_name }}">
            </div>
            <div class="form-group">
                <label for="description">Email</label>
                <input class="form-control @error('email') is-invalid @enderror" type="text" name="email" value="{{ $reservation->email }}">
            </div>
            <div class="form-group">
                <label for="description">Telefon</label>
                <textarea class="form-control" name="phone" id="exampleFormControlTextarea1">{{ $reservation->phone }}</textarea>
            </div>
            <div class="form-group">
                <label for="name" class="form-label">Data rezerwacji</label>
                <div class="mt-1">
                    <input type="datetime-local" id="res_date" name="res_date" class="data @error('res_date') is-invalid @enderror" value="{{ $reservation->res_date }}"/>
                    @error('first_name')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                    @error('res_date')
                        <div class="text-sm text-red-400">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="form-group">
                <label for="description">Stolik</label>
                <select class="form-control" id="table_id" name="table_id">
                    @foreach ($tables as $table)
                        <option value="{{ $table->id }}" @selected($table->id == $reservation->table_id)>{{ $table->name }}
                            ({{ $table->guest_number }} Liczba miejsc)
                        </option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label for="description">Liczba gości</label>
                <textarea class="form-control" name="guest_number" id="exampleFormControlTextarea1">{{ $reservation->guest_number }}</textarea>
            </div>

            <button type="submit" class="btn btn-primary">Aktualizuj</button>
        </form>
    </div>
</div>
@endsection

resources/views/admin/reservations/index.blade.php
@extends('layouts.mainAdmin')
@section('content')

<div class="main">
    <h1>Rezerwacje</h1>

    <div class="">
        <a class="btn btn-dark" href="{{ route('admin.reservations.create') }}" role="button">Nowa kategoria</a>
    </div>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Nr</th>
                <th scope="col">Imie</th>
                <th scope="col">Nazwisko</th>
                <th scope="col">email</th>
                <th scope="col">Telefon</th>
                <th scope="col">Data rezerwacji</th>
                <th scope="col">Numer stolika</th>
                <th scope="col">Numer klienta</th>
                <th scope="col" id="table_akcja">Akcja</th>
            </tr>
            </thead>
            <tbody>
                @foreach ($reservations as $reservation )
                    <tr>
                        <th scope="row">{{ $loop->iteration }}</th>
                        <td>{{ $reservation->first_name	 }}</td>
                        <td>{{ $reservation->last_name }}</td>
                        <td>{{ $reservation->email }}</td>
                        <td>{{ $reservation->phone }}</td>
                        <td>{{ $reservation->res_date }}</td>
                        <td>{{ $reservation->table->name  ?? 'Brak Stolika' }}</td>
                        <td>{{ $reservation->guest_number }}</td>
                        <td>
                            <a class="btn btn-dark" href="{{ route('admin.reservations.edit', $reservation->id) }}" role="button">Edytuj</a>
                            <form method="POST" action="{{ route('admin.reservations.destroy', $reservation->id) }}" onsubmit="return confirm('Na pewno chcesz usunąć?');">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger" type="submit" role="button">Usuń</button>
                        </form>
                        </td>
                    </tr>
                @endforeach
        </tbody>
    </table>
</div>
@endsection