routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\TableController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Front\FrontMenuController;
use App\Http\Controllers\Admin\ReservationController;
use App\Http\Controllers\Front\FrontWelcomeController;
use App\Http\Controllers\Front\FrontCategoryController;
use App\Http\Controllers\Front\FrontReservationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');


Route::get('/', [FrontWelcomeController::class, 'index']);
Route::get('/menu', [FrontMenuController::class, 'index'])->name('menu.index');
Route::get('/categories', [FrontCategoryController::class, 'index'])->name('categories.index');
Route::get('/categories/{category}', [FrontCategoryController::class, 'show'])->name('categories.show');
Route::get('/reservation/step-one', [FrontReservationController::class, 'stepOne'])->name('reservation.step-one');
Route::post('/reservation/step-one', [FrontReservationController::class, 'storeStepOne'])->name('reservation.store.step-one');
Route::get('/reservation/step-two', [FrontReservationController::class, 'stepTwo'])->name('reservation.step-two');
Route::post('/reservation/step-two', [FrontReservationController::class, 'storeStepTwo'])->name('reservation.store.step-two');

// Admin

Route::middleware(['auth', 'admin'])->name('admin.')->prefix('admin')->group(function(){
    Route::get('/', [AdminController::class, 'index'])->name('index');
    Route::resource('/categories', CategoryController::class);
    Route::resource('/menus', MenuController::class);
    Route::resource('/tables', TableController::class);
    Route::resource('/reservations', ReservationController::class);
});



require __DIR__.'/auth.php';

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable =[
        'name',
        'image',
        'description'
    ];

    public function menu()
    {
        return $this->belongsToMany(Menu::class, 'category_menu');
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\CategoryStoreRequest;
use Illuminate\Support\Facades\Storage;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::paginate(4);
        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryStoreRequest $request)
    {
        $category = new Category($request->validated());
        if ($request->hasFile('image')){
            $category->image = $request->file('image')->store('products');
        }
        $category->save();

        return redirect(route('admin.categories.index'))->with('success','');
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('admin.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryStoreRequest $request, Category $category)
    {

        $category->fill($request->all());
        if ($request->hasFile('image')){
            $category->image = $request->file('image')->store('products');
        }
        $category->save();

        return redirect(route('admin.categories.index'))->with('warning','');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->menu()->detach();
        $category->delete();
        return redirect(route('admin.categories.index'))->with('danger','');
    }
}

resources/views/admin/categories/create.blade.php
@extends('layouts.mainAdmin')
@section('content')

<div class="main">
    <h1>Categories</h1>

    <div class="">
        <a class="btn btn-dark button-back" href="{{ route('admin.categories.index') }}" role="button">Powrót do karegori</a>

    </div>

    <div class="smal main">
        <form method="POST" action="{{ route('admin.categories.store') }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="name" class="form-label">Nazwa kategorii</label>
                <input class="form-control @error('name') is-invalid @enderror" type="text" name="name" placeholder="Nazwa kategorii">
                @error('name')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="image" class="form-label" >Zdjęcie</label>
                <input class="form-control @error('image') is-invalid @enderror" type="file" name="image" id="formFile">
                @error('image')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="description" >Opis</label>
                <textarea class="form-control @error('description') is-invalid @enderror" name="description" id="exampleFormControlTextarea1" rows="3"></textarea>
                @error('description')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.mainAdmin')
@section('content')

<div class="main">
    <h1>Categories Edit</h1>

    <div class="">
        <a class="btn btn-dark button-back" href="{{ route('admin.categories.index') }}" role="button">Powrót do karegori</a>

    </div>

    <div class="smal main">
        <form method="POST" action="{{ route('admin.categories.update',$category->id) }}" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group">
                <label for="name" class="form-label">Default file input example</label>
                <input class="form-control" type="text" name="name" value="{{ $category->name }}">
            </div>
            <div class="mb-3">
                <label for="image" class="form-label" >Default file input example</label>
                <input class="form-control" type="file" name="image" id="formFile" src="{{ asset('storage/' . $category->image) }}">
            </div>
            <div class="form-group">
                <label for="description" >Example textarea</label>
                <textarea class="form-control" name="description" id="exampleFormControlTextarea1">{{ $category->description }}</textarea>
            </div>
            <button type="submit" class="btn btn-primary" >Submit</button>
        </form>
    </div>
</div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.mainAdmin')
@section('content')

<div class="main">
    <h1>Kategorie</h1>

    <div class="">
        <a class="btn btn-dark" href="{{ route('admin.categories.create') }}" role="button">Nowa kategoria</a>
    </div>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Nr</th>
                <th scope="col">Nazwa</th>
                <th scope="col">Zdjęcie</th>
                <th scope="col">Opis</th>
                <th scope="col" id="table_akcja">Akcja</th>
            </tr>
            </thead>
            <tbody>
                @foreach ($categories as $category )
                    <tr>
                        <th scope="row">{{ $loop->iteration }}</th>
                        <td>{{ $category->name }}</td>
                        <td><img class="image_index" src="{{ asset('storage/' . $category->image) }}"></td>
                        <td>{{ $category->description }}</td>
                        <td>
                            <a class="btn btn-dark" href="{{ route('admin.categories.edit', $category->id) }}" role="button">Edytuj</a>
                            <form method="POST" action="{{ route('admin.categories.destroy', $category->id) }}" onsubmit="return confirm('Na pewno chcesz usunąć?');">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger" type="submit" role="button">Usuń</button>
                        </form>
                        </td>
                    </tr>
                @endforeach
        </tbody>

    </table>
    {{ $categories->links() }}
</div>
@endsection